### ISSUE TITLE
Highlight of selected opponent filter

### ISSUE THREAD

**Issue by MrFuNK1** [Cselt/rf2-better-ui#7]
Location:
Session > Opponents > Opponent Filter

What:
Highlight of selected opponent filter (currently no highlight)

**Comment by Cselt** [comment]
It does work for me. Can you please double check? Can you see the small Better-UI label on the bottom right corner?

![opponent filter](https://user-images.githubusercontent.com/11027521/105635394-d5b2c180-5e62-11eb-9c56-9cab7d786829.png)
