### ISSUE TITLE
Install path

### ISSUE THREAD

**Issue by TrickyDee42** [Cselt/rf2-better-ui#9]
Since you have added the installer, it thinks my install is on F: it isn't it is on D:

rF2 runs fine, so guess the reg entry is not affecting the game, just the install. Can you add an option to install to a location even if it finds the location in the registry.

R.

**Comment by TrickyDee42** [comment]
Found the reg entry, so sorted now, but thanks for looking into it anyway.

**Comment by Cselt** [comment]
Will be fixed in the next release, installer will ask for the install location.
